analyzers:
  ros__parameters:
    path: mubot
    sensors:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Sensors
      contains: [imu, range, camera]
    control:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Control
      contains: [behavior, gait_generator, actuator]
    localization:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Localization
      contains: [ekf, slam, gait_odometry]
